import { Link } from 'react-router-dom'

export default function Terms() {
  return (
    <div className="min-h-screen bg-[#f6fafa] font-sans text-[#181c1d] flex flex-col justify-between">
      
      {/* Top Navbar */}
      <nav className="bg-white border-b border-slate-200 py-4 px-6 md:px-16 flex justify-between items-center max-w-[1200px] mx-auto w-full">
        <Link to="/" className="font-serif text-2xl font-bold text-slate-900">
          MedGuard
        </Link>
        <Link to="/login" className="text-sm font-semibold text-[#0F766E] hover:text-[#0d645e]">
          Sign In
        </Link>
      </nav>

      {/* Main Content */}
      <main className="max-w-[800px] mx-auto px-6 py-16 flex-grow text-left">
        <h1 className="font-sans text-5xl font-bold text-slate-900 mb-6">Terms of Service</h1>
        <p className="text-xs text-slate-400 mb-10">Last updated: July 15, 2026</p>

        <section className="space-y-8 text-sm text-slate-600 leading-relaxed">
          <div>
            <h2 className="text-lg font-bold text-slate-900 mb-3">1. Non-Diagnostic Consultation Helper</h2>
            <p>
              MedGuard is an AI-powered safety check helper. All drug interactions, structural extracts, and trend representations generated by this platform are for informational, preparation support purposes only. MedGuard is NOT a diagnostic medical service, and should never be used as a replacement for clinical advice or treatment changes.
            </p>
          </div>

          <div>
            <h2 className="text-lg font-bold text-slate-900 mb-3">2. User Responsibility</h2>
            <p>
              Patients and caregivers must verify all extracted information (medications, dosages, frequencies, and lab values) against the original physician-issued documents before saving them. You assume full responsibility for any treatment decisions made in consultation with your healthcare provider.
            </p>
          </div>

          <div>
            <h2 className="text-lg font-bold text-slate-900 mb-3">3. Caregiver Access Control</h2>
            <p>
              By sharing caregiver linking passcodes, patients explicitly consent to granting the linked caregiver full view and read access to their clinical profiles, medication lists, safety warning logs, and lab analysis summaries. Patients retain the right to revoke this linkage instantly at any time.
            </p>
          </div>

          <div className="bg-[#f0f7f7] border-l-4 border-[#0f766e] p-5 rounded-r-lg mt-8">
            <h3 className="text-sm font-bold text-[#00504a] mb-2">Clinical Safety Advisory</h3>
            <p className="text-xs text-slate-600">
              Never initiate, discontinue, or alter any medication dosage without explicit instructions from a certified clinical practitioner.
            </p>
          </div>
        </section>
      </main>

      {/* Footer */}
      <footer className="bg-white border-t border-slate-200 py-8 text-center text-xs text-slate-400">
        <div className="max-w-[1200px] mx-auto px-6 flex flex-col md:flex-row justify-between items-center gap-4">
          <span>© 2026 MedGuard AI. All rights reserved.</span>
          <div className="flex gap-4">
            <Link to="/privacy-policy" className="hover:text-slate-600">Privacy Policy</Link>
            <Link to="/support" className="hover:text-slate-600">Support</Link>
          </div>
        </div>
      </footer>
    </div>
  )
}
